# -*- coding: utf-8 -*-
"""Netflix_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nox3TNsgKkJUbTnM_yck1iufr0KGVGm2

##      "Netflix Content Analysis: Exploring Diversity, Popularity, and Duration."
Netflix is one of the most popular media and video streaming platforms. They have over 8000 movies or tv shows available on their platform, as of mid-2021, they have over 200M Subscribers globally. This tabular dataset consists of listings of all the movies and tv shows available on Netflix, along with details such as - cast, directors, ratings, release year, duration, etc.
"""

##1. Load the dataset and print the complete information of the dataset and name the columns that has missing values.


import pandas as pd

netflix=pd.read_csv("netflix.csv")
print(netflix.info())
print("columns that has missing values are director,cast,country")

##2.Load the dataset and print the top 10 countries contributing to the Content on Netflix

import pandas as pd

netflix=pd.read_csv("netflix.csv")
print(netflix["country"].value_counts().head(10))

##3.Load the dataset and list the 5 most popular types of genre on the platform.

import pandas as pd
netflix=pd.read_csv("netflix.csv")
genre_count=netflix["listed_in"].str.split(", ").explode().value_counts()
print(genre_count.head(5))

##4.Load the Dataset and categorize into TV shows and Movies and display 2 rows for each.

import pandas as pd
netflix=pd.read_csv("netflix.csv")
movies=netflix[netflix["type"]=="Movie"]
Tvshows=netflix[netflix["type"]=="TV Show"]
print(movies.head(2))
print(Tvshows.head(2))

##5. Load the Dataset and find the Oldest movies

import pandas as pd
netflix=pd.read_csv("netflix.csv")
movies=netflix[netflix["type"]=="Movie"]
print(movies[movies["release_year"]==movies["release_year"].min()]["title"])

##6. Load the Dataset and get the count of values for duration column.

import pandas as pd
import numpy as np
netflix=pd.read_csv("netflix.csv")
print(netflix.duration.value_counts())

##7. Load the Dataset and find the measures of central tendency and dispersion of duration column by extracting  numerical part of the duration column.

# code goes here
import pandas as pd

netflix=pd.read_csv("netflix.csv")
netflix["duration1"]=netflix["duration"].str.extract("(\d+)",expand=False).astype("float")
print("The mean duration is",netflix["duration1"].mean())
print("The highest duration is",netflix["duration1"].max())
print("The minimum duration is",netflix["duration1"].min())
print("The variance of duration is",netflix["duration1"].var())
print("The standard deviation is",netflix["duration1"].std())

##8. Load the Dataset and find out to which country the highest duration movie belongs to by extracting the numerical part of the duration column and create a new column.
# print title and country column.

import pandas as pd
import numpy as np
netflix=pd.read_csv("netflix.csv")
netflix["duration1"]=netflix["duration"].str.extract("(\d+)",expand=False).astype("float")
print(netflix[netflix["duration1"]==netflix["duration1"].max()][["title","country"]])

##9. Load the Dataset and plot the histogram  on Netflix Content Release Year Distribution


import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
netflix=pd.read_csv("netflix.csv")
import plotly.express as px
px.histogram(netflix,x="release_year",title="year wise count")

##10. Load the Dataset and plot the Distribution of Populartiy of different content categories using countplot

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
netflix=pd.read_csv("netflix.csv")
ax=sns.countplot(data=netflix,y="listed_in", order=netflix["listed_in"].value_counts().index[0:20])
ax.bar_label(ax.containers[0]) # to get values next to graphs

plt.show()